import React,{useState,useEffect}from'react';
import{View,Text,FlatList,TouchableOpacity,TextInput,StyleSheet,ScrollView,Alert}from'react-native';
import AsyncStorage from'@react-native-async-storage/async-storage';
import{NavigationContainer}from'@react-navigation/native';
import{createBottomTabNavigator}from'@react-navigation/bottom-tabs';
import{createNativeStackNavigator}from'@react-navigation/native-stack';
import{Ionicons}from'@expo/vector-icons';
import{StatusBar}from'expo-status-bar';
import{feelings,shadowPrompts,dreamSymbols}from'./data/feelings';
const Tab=createBottomTabNavigator();const Stack=createNativeStackNavigator();
function Badge(){return <Text style={s.badge}>Premium</Text>}
function Upgrade(){return <View style={s.upgrade}><Text style={s.upTitle}>Unlock Premium</Text><Text style={s.body}>AI Coach, Voice Journal, Shadow Work, Dream Journal, Insights, weekly reports, and no ads.</Text><Text style={s.price}>$3.99/month or $29.99/year</Text><TouchableOpacity style={s.btn}><Text style={s.btnText}>Start 7-Day Free Trial</Text></TouchableOpacity></View>}
function Feelings({navigation}){return <View style={s.container}><Text style={s.title}>Emotion Compass ⭐</Text><Text style={s.sub}>Understand what your feelings may mean.</Text><FlatList data={feelings} numColumns={2} keyExtractor={i=>i.id} renderItem={({item})=><TouchableOpacity style={s.card} onPress={()=>navigation.navigate('Detail',{id:item.id})}><Text style={s.emoji}>{item.emoji}</Text><Text style={s.cardTitle}>{item.name}</Text></TouchableOpacity>}/></View>}
function Detail({route}){let f=feelings.find(x=>x.id===route.params.id);return <ScrollView style={s.container}><Text style={s.big}>{f.emoji}</Text><Text style={s.title}>{f.name}</Text><Text style={s.h}>What it may mean</Text><Text style={s.body}>{f.meaning}</Text><Text style={s.h}>Reflection questions</Text>{f.questions.map((q,i)=><Text key={i} style={s.q}>• {q}</Text>)}<Text style={s.note}>Educational only. Not medical or mental health treatment.</Text></ScrollView>}
function FeelStack(){return <Stack.Navigator><Stack.Screen name='FeelingsHome' component={Feelings} options={{title:'Emotion Compass'}}/><Stack.Screen name='Detail' component={Detail} options={{title:'Feeling Meaning'}}/></Stack.Navigator>}
function Journal(){const[entry,setEntry]=useState('');const[entries,setEntries]=useState([]);useEffect(()=>{AsyncStorage.getItem('entries').then(v=>v&&setEntries(JSON.parse(v)))},[]);async function save(){if(!entry.trim())return Alert.alert('Write an entry first.');let n=[{id:Date.now().toString(),text:entry,date:new Date().toLocaleString()},...entries];setEntries(n);setEntry('');await AsyncStorage.setItem('entries',JSON.stringify(n))}return <ScrollView style={s.container}><Text style={s.title}>Journal</Text><Text style={s.sub}>Write what happened, what you felt, and what you need.</Text><TextInput style={s.input} multiline placeholder='Today I feel...' value={entry} onChangeText={setEntry}/><TouchableOpacity style={s.btn} onPress={save}><Text style={s.btnText}>Save Entry</Text></TouchableOpacity><View style={s.entry}><Badge/><Text style={s.cardTitle}>Voice Journal</Text><Text style={s.body}>Record voice notes and turn them into searchable entries.</Text></View>{entries.map(e=><View key={e.id} style={s.entry}><Text style={s.date}>{e.date}</Text><Text style={s.body}>{e.text}</Text></View>)}</ScrollView>}
function Coach(){const[msg,setMsg]=useState('');const[reply,setReply]=useState('Tell me what you are feeling.');return <ScrollView style={s.container}><Text style={s.title}>AI Emotion Coach</Text><Badge/><Text style={s.sub}>Premium chat guide for emotional awareness.</Text><View style={s.entry}><Text style={s.body}>{reply}</Text></View><TextInput style={s.inputSmall} placeholder='Example: I feel angry at work...' value={msg} onChangeText={setMsg}/><TouchableOpacity style={s.btn} onPress={()=>{setReply('That feeling may point to an unmet need, crossed boundary, or fear. What happened right before it showed up?');setMsg('')}}><Text style={s.btnText}>Ask Emotion Compass</Text></TouchableOpacity><Text style={s.note}>This is a demo coach screen. Real AI can be connected later.</Text></ScrollView>}
function More(){return <ScrollView style={s.container}><Text style={s.title}>More Tools</Text>{['Calm Tools','Shadow Work','Dream Journal','Insights'].map((t,i)=><TouchableOpacity key={i} style={s.entry}><Text style={s.cardTitle}>{t}</Text></TouchableOpacity>)}<Text style={s.h}>Shadow Work</Text>{shadowPrompts.map((p,i)=><Text key={i} style={s.q}>• {p}</Text>)}<Text style={s.h}>Dream Symbols</Text>{dreamSymbols.map((d,i)=><Text key={i} style={s.q}>• {d[0]}: {d[1]}</Text>)}<Text style={s.h}>Calm Tool</Text><Text style={s.body}>Box breathing: inhale 4, hold 4, exhale 4, hold 4.</Text></ScrollView>}
function Premium(){return <ScrollView style={s.container}><Text style={s.title}>Go Premium</Text><Upgrade/><Text style={s.h}>Included</Text>{['AI Emotion Coach','Voice Journal','Shadow Work','Dream Journal','Insights Dashboard','Weekly Reports','No Ads'].map((x,i)=><Text key={i} style={s.q}>✓ {x}</Text>)}<Text style={s.note}>Payments can be connected later using Google Play Billing or RevenueCat.</Text></ScrollView>}
export default function App(){return <NavigationContainer><StatusBar style='dark'/><Tab.Navigator screenOptions={({route})=>({headerShown:false,tabBarActiveTintColor:'#6B4EFF',tabBarIcon:({color,size})=><Ionicons name={({Feelings:'heart-outline',Journal:'book-outline',Coach:'chatbubble-outline',Premium:'star-outline',More:'grid-outline'})[route.name]} size={size} color={color}/>})}><Tab.Screen name='Feelings' component={FeelStack}/><Tab.Screen name='Journal' component={Journal}/><Tab.Screen name='Coach' component={Coach}/><Tab.Screen name='Premium' component={Premium}/><Tab.Screen name='More' component={More}/></Tab.Navigator></NavigationContainer>}
const s=StyleSheet.create({container:{flex:1,backgroundColor:'#F7F3EA',padding:20},title:{fontSize:30,fontWeight:'800',color:'#242038',marginBottom:8},sub:{fontSize:16,color:'#5F5A6B',marginBottom:20,lineHeight:23},card:{backgroundColor:'#fff',width:'47%',margin:'1.5%',padding:20,borderRadius:20,minHeight:130,justifyContent:'center',alignItems:'center',elevation:2},emoji:{fontSize:38,marginBottom:8},big:{fontSize:70,textAlign:'center'},cardTitle:{fontSize:18,fontWeight:'700',color:'#242038'},h:{fontSize:20,fontWeight:'800',color:'#242038',marginTop:22,marginBottom:8},body:{fontSize:16,color:'#343044',lineHeight:24},q:{fontSize:16,color:'#343044',lineHeight:26,marginBottom:5},note:{backgroundColor:'#FFF6D8',color:'#5E4A00',padding:14,borderRadius:14,marginTop:24,lineHeight:22},input:{minHeight:140,backgroundColor:'#fff',borderRadius:16,padding:14,fontSize:16,textAlignVertical:'top',marginBottom:14},inputSmall:{minHeight:70,backgroundColor:'#fff',borderRadius:16,padding:14,fontSize:16,textAlignVertical:'top',marginBottom:14},btn:{backgroundColor:'#6B4EFF',padding:15,borderRadius:14,alignItems:'center',marginTop:12,marginBottom:20},btnText:{color:'#fff',fontSize:16,fontWeight:'800'},entry:{backgroundColor:'#fff',padding:15,borderRadius:16,marginBottom:12},date:{color:'#777',marginBottom:8,fontSize:12},badge:{alignSelf:'flex-start',backgroundColor:'#242038',color:'#fff',paddingHorizontal:10,paddingVertical:5,borderRadius:999,fontWeight:'800',marginBottom:12},upgrade:{backgroundColor:'#fff',padding:18,borderRadius:20,marginBottom:20,borderWidth:1,borderColor:'#E4DDFD'},upTitle:{fontSize:22,fontWeight:'900',color:'#242038',marginBottom:8},price:{fontSize:18,fontWeight:'900',color:'#6B4EFF',marginTop:12}});
